name: stroke-risk-deployment
flow_name: stroke_risk_pipeline
entrypoint: flows/pipeline_flow.py:stroke_risk_pipeline
work_pool:
  name: local-process-pool
schedules:
  - interval:
      seconds: 900  # 15 minutes
    active: true