name: token-refresh-deployment
flow_name: token_refresh_pipeline
entrypoint: flows/pipeline_flow.py:token_refresh_pipeline
work_pool:
  name: local-process-pool
schedules:
  - interval:
      seconds: 21600  # 6 hours
    active: true